package_assets: on
compress_assets: on
embed_assets: off
javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/application.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/notes/new.js
    - public/javascripts/notes/index.js
    - public/javascripts/routes.js
    - public/javascripts/notes/note.js
    - app/views/notes/*.jst
    - public/javascripts/tags/*.js
  note_cloud:
    - public/javascripts/note_cloud.js
  twitter_bootstrap:
    - public/javascripts/bootstrap-buttons.js
    - public/javascripts/bootstrap.min.js
stylesheets:
  common:
    - public/stylesheets/application.css
    - public/stylesheets/form_style.css
  note_cloud:
    - public/stylesheets/custom.css
    - public/stylesheets/tag_cloud.css
  twitter_bootstrap:
    - public/stylesheets/bootstrap.css
    
